### ISSUE TITLE
there is no goyo king in Breakers of Shadow script

### ISSUE THREAD

**Issue by StanTysco246** [ygohack137/ygohack137#11]

**Comment by mercury233** [comment]
https://github.com/ygohack137/ygohack137/blob/master/Breaker%20of%20Shadow/script/c13790626.lua

**Comment by StanTysco246** [comment]
![ygopro_1199923](https://cloud.githubusercontent.com/assets/13827071/10251001/4e2dad10-6958-11e5-8162-6d3a11a57df2.png)

**Comment by StanTysco246** [comment]
i can't find goyo king card in ygopro

**Comment by mercury233** [comment]
http://yugioh.wikia.com/wiki/Goyo_King
http://yugioh.wikia.com/wiki/Goyo_Emperor
It was different cards.
Here are their scripts.
https://github.com/ygohack137/ygohack137/blob/master/Breaker%20of%20Shadow/script/c13790626.lua
https://github.com/ygohack137/ygohack137/blob/master/Breaker%20of%20Shadow/script/c13790613.lua

**Comment by StanTysco246** [comment]
but i found goyo king card script, but that script isn't added to BOSH. Can you help me?

**Comment by StanTysco246** [comment]
i have checked bosh in expansions folder. there isn't any goyo king description.

**Comment by mercury233** [comment]
I think that your ygopro just hadn't updated goyo king yet....

**Comment by StanTysco246** [comment]
can you help me to update goyo king?

**Comment by mercury233** [comment]
Sorry I can't. You can contact the admin of your ygopro. Or maybe somebody will release a update in a few days.
